# Human Tasks:
# 1. Ensure namespaces 'fleet-tracking' and 'monitoring' exist before applying
# 2. Configure network policies to restrict pod communication
# 3. Set up secret management for service account tokens
# 4. Monitor service account usage through audit logs
# 5. Regularly rotate service account tokens

# Requirement: Authentication and Authorization (8.1 Authentication and Authorization/8.1.2 Authorization Model)
# Service account for location tracking service with restricted permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: location-service-account
  namespace: fleet-tracking
  labels:
    app: fleet-tracking
    component: location-service
    security-tier: restricted
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/description: "Service account for location tracking service with restricted permissions"
    # Requirement: Security Controls (4.6 Security Architecture/Security Services)
    # Associates service account with restricted pod security policy
    security.kubernetes.io/pod-security-policy: restricted-psp

---
# Requirement: Authentication and Authorization (8.1 Authentication and Authorization/8.1.2 Authorization Model)
# Service account for fleet management service with restricted permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-service-account
  namespace: fleet-tracking
  labels:
    app: fleet-tracking
    component: fleet-service
    security-tier: restricted
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/description: "Service account for fleet management service with restricted permissions"
    # Requirement: Compliance Requirements (8.3.3 Security Compliance Controls)
    # Enforces pod security policy for SOC 2 and ISO 27001 compliance
    security.kubernetes.io/pod-security-policy: restricted-psp

---
# Requirement: Authentication and Authorization (8.1 Authentication and Authorization/8.1.2 Authorization Model)
# Service account for analytics service with restricted permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-account
  namespace: fleet-tracking
  labels:
    app: fleet-tracking
    component: analytics-service
    security-tier: restricted
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/description: "Service account for analytics service with restricted permissions"
    # Requirement: Security Controls (4.6 Security Architecture/Security Services)
    # Implements identity management with proper isolation
    security.kubernetes.io/pod-security-policy: restricted-psp

---
# Requirement: Authentication and Authorization (8.1 Authentication and Authorization/8.1.2 Authorization Model)
# Service account for monitoring components with elevated permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account
  namespace: monitoring
  labels:
    app: fleet-tracking
    component: monitoring
    security-tier: privileged
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/description: "Service account for monitoring components with elevated permissions"
    # Requirement: Security Controls (4.6 Security Architecture/Security Services)
    # Assigns privileged PSP for monitoring components that require elevated access
    security.kubernetes.io/pod-security-policy: privileged-psp